name: Jacoco-report
on:
  pull_request:
jobs:
  codicity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        env:
          GITHUB_USER: ${{secrets.bnauk_user}}
          GITHUB_TOKEN: ${{secrets.bnauk_token}}
        run: mvn clean test jacoco:report
      - name: Generate Jacoco Badge
        id: jacoco-badge
        uses: cicirello/jacoco-badge-generator@v1.0.0
      - name: Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@fd4800e8a81e21bdf373438e5918b975df041d15
        with:
          paths: target/site/jacoco/jacoco.xml
          token: ${{secrets.bnauk_token}}
          min-coverage-overall: 50
          min-coverage-changed-files: 50
      - name: Log coverage percentage
        run: |
          echo "Total coverage: ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Total coverage Overall: ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage: ${{ steps.jacoco.outputs.coverage-changed-files }}"
      - name: Cache artifact Build
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: build-${{ github.sha }}
