name: Jacoco-report
on:
  push:
    branches: [ develop, main]
jobs:
  codicity:
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Build with Maven
          env:
            GITHUB_USER: ${{secrets.bnauk_user}}
            GITHUB_TOKEN: ${{secrets.bnauk_token}}
          run: mvn clean test jacoco:report
        - name: Generate Jacoco Badge
          id: jacoco
          uses: cicirello/jacoco-badge-generator@v1.0.0

        - name: Upload Jacoco coverage report
          uses: actions/upload-artifact@v2
          with:
            name: jacoco-report
            path: target/site/jacoco/test/testCoverage.xml
        - name: Report to PR
          id: jacoco
          uses: madrapps/jacoco-report@v1.1
          with:
            path: target/site/jacoco/test/testCoverage.xml
            token: ${{secrets.bnauk_token}}
            min-coverage-overall: 80
            min-coverage-changed-files: 80
            debug-mode: false
        - name: Log coverage percentage
          run: |
            echo "Total coverage: ${{ steps.jacoco.outputs.coverage-overall }}"
            echo "Total coverage Overall: ${{ steps.jacoco.outputs.coverage-overall }}"
            echo "Changed Files coverage: ${{ steps.jacoco.outputs.coverage-changed-files }}"
        - name: Cache artifact Build
          uses: actions/cache@v2
          id: restore-build
          with:
            path: ./*
            key: build-${{ github.sha }}
